name: autoBuild
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-statistics-plugin
      - run: pip install mkdocs-heti-plugin
      - run: mkdocs gh-deploy --force
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          keep_files: true
          
